In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("COASAMPLE.csv")
data.head()

Year  UNITID  INTUTIONFEE  OUTTUTIONFEE  BOOKSUPPLY  ONCAMROOM  \
0  2016  100751        10470         26950      1200.0      13050   
1  2016  100858        10696         28840      1200.0      12898   
2  2016  101453         9792          9792      1000.0       4140   
3  2016  102298        12340         12340      1370.0       6504   
4  2016  106412         6898         12988      1000.0       7372   

   ONCAMOTHEXP  OFFCAMROOM  OFFCAMOTHEXP  Total  AllocProportion  SampleSize  \
0         4116       13050          4116   1368             0.25         125   
1         5664       12898          5664   1368             0.25         125   
2         2628       10503          3456   1368             0.25         125   
3         2100        3200          2100   1368             0.25         125   
4         2848        4426          3888   1368             0.25         125   

   ActualProportion  SelectionProb  SamplingWeight  
0              0.25       0.091374          10.944  
1              0.25       0.091374          10.944  
2              0.25       0.091374          10.944  
3              0.25       0.091374          10.944  
4              0.25       0.091374          10.944

In [3]:
data.shape

(480, 15)

In [4]:
data_df = pd.DataFrame(data, columns = ['Year', 'UNITID', 'INTUTIONFEE','OUTTUTIONFEE','BOOKSUPPLY','ONCAMROOM','ONCAMOTHEXP','OFFCAMROOM','OFFCAMOTHEXP'])
data_df.shape

(480, 9)

In [5]:
data_x = pd.DataFrame(data_df, columns=['INTUTIONFEE']).values
data_x.shape

(480, 1)

In [6]:
data_y1 = pd.DataFrame(data_df, columns=['OUTTUTIONFEE']).values
data_y2 = pd.DataFrame(data_df, columns=['ONCAMROOM']).values
data_y3 = pd.DataFrame(data_df, columns=['OFFCAMROOM']).values
#res = data_y.reshape([499, 499])
data_y1.shape

(480, 1)

In [7]:
outtutionfee_model = LinearRegression().fit(data_x,data_y1)
oncampusroom_model = LinearRegression().fit(data_x,data_y2)
offcampusroom_model = LinearRegression().fit(data_x,data_y3)

In [8]:
r_sq = outtutionfee_model.score(data_x,data_y1)
print('coefficient of determination:', r_sq)
print('intercept:', outtutionfee_model.intercept_)
print('slope:', outtutionfee_model.coef_)

coefficient of determination: 0.8037645877204754
intercept: [10528.09509374]
slope: [[0.72436645]]


In [9]:
print("Predicted Out of Station Tution Fees")
print(outtutionfee_model.predict([[22340], [17092]]))

Predicted Out of Station Tution Fees
[[26710.44165086]
 [22908.9665062 ]]


In [10]:
print("Predicted On campus housing")
print(oncampusroom_model.predict([[22340], [17092]]))

Predicted On campus housing
[[10557.55820359]
 [10028.05047583]]


In [11]:
print("Predicted On campus housing")
print(offcampusroom_model.predict([[22340], [17092]]))

Predicted On campus housing
[[10077.45151252]
 [ 9777.73380568]]
